# _config.yml

# Welcome to SRE

# Site settings
# These are used to personalize your new site. If you remove this file, Jekyll will stop working.
# Learn more about Jekyll at https://jekyllrb.com/docs/configuration/
kramdown:
  auto_ids: true
  auto_id_prefix: "markdown-"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
    span:
      line_numbers: false

# Site Settings
locale: "ja-JP" # 日本語設定
title: "SRE Data Analytics Knowledge Base"
title_separator: "|"
name: "LCP Business SRE"
description: "Minimal Mistakesテーマを使った教材サイトのサンプルです。"
url: "https://lcp-business-sre.github.io" # Base URL of site (e.g. https://foo.github.io or https://www.example.com)
baseurl: "knowledge-base-for-leveraging-data-analytics" # the subpath of your site, e.g. /blog
repository: "knowledge-base-for-leveraging-data-analytics" # GitHubリポジトリ名 (必要に応じて)
words_per_minute: 200 # 読書時間の計算用
# analytics:
#   provider: "google" # Google Analytics (不要ならコメントアウト)
#   google:
#     tracking_id: "UA-XXXXXXXXX-X"

# Minimal Mistakes theme settings
minimal_mistakes_skin: "default" # "default", "air", "aqua", "contrast", "dark", "dirt", "forest", "light", "mint", "sunrise" など
# この行を削除して、_sass/custom/_colors.scss で完全に色を制御します

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0" # Minimal Mistakesテーマを指定
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-remote-theme
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be re-enabled by adding them to the `include:` list of the document `_config.yml`.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - docs/ # Minimal Mistakesのドキュメント（削除可能）
  - CNAME # GitHub Pagesカスタムドメイン用（不要なら削除）

# Site Author
author:
  name: "SRE Data Analytics Team" # 著者名
  avatar: "/assets/images/bio-photo.jpg" # アバター画像パス (必要なら設定)
  bio: "SRE Data Analytics Team"
  uri: "https://sites.google.com/mb.lecip.co.jp/business-dx/dx-sol"
  email: "your@email.com"
  github: "your_github_username"

# Jekyll settings
defaults:
  # _pages 内のすべてのMarkdownファイルに page レイアウトを適用
  - scope:
      path: "_pages"
    values:
      layout: "page"
      # サイドバーのナビゲーションを有効にするための設定
      sidebar:
        nav: "docs" # _data/navigation.yml で定義したサイドバーナビゲーションID
      # 目次を自動生成する場合 (toc: true)
      # toc: true
      # toc_label: "目次"
      # toc_icon: "fa-solid fa-list"
      # toc_sticky: true # サイドバーに固定表示

# ナビゲーション設定 (トップメニュー)
# _data/navigation.yml で設定するが、ここでは例としてコメントアウト
# main:
#   - title: "ホーム"
#     url: /
#   - title: "第1章"
#     url: /chapter1/
#   - title: "第2章"
#     url: /chapter2/

# Pagination
paginate: 5
paginate_path: /page:num/

